---
title: "About"
author: "Matej Cerman"
date: "29 2 2020"
output: html_document
---

This project will explore educational outcomes of primary and secondary schools in Slovakia in connection to regional disparities in socioeconomic factors, mainly income.

The first dataset used comes from INEKO, a Slovak think-tank which compiles [yearly rankings](http://skoly.sme.sk/rebricky/) of public schools primarily calculated by looking at standardized testing and college admissions. INEKO publishes its data, using a separate file to store basic information about 3777 schools and then a file for each year of the rankings which stores information about the outcomes of various assessments. All in all, I will be using 11 datasets from INEKO to look at the last 10 years of school rankings.

The second source of data is the [dataset portal](data.gov.sk) of the Slovak government. I will be using their "key economic and social indicators" dataset compiled by the Slovak Statistical Office to look at the average income, unemployment rate, and average educational level in Slovak counties in order to visualize and estimate the impact of economic factors on the performance of students. INEKO istelf admits that they do not have a methodology for looking at the inherent quality of schools and therefore use students' test scores as a heuristic, which makes the rankings susceptible to the effects of confounding variables, mainly socioeconomic factors. By using both of these sources of data, I'm hoping to examine these effects. 