---
title: "Project Data Analysis"
author: "Matej Cerman"
date: "19 4 2020"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('gather.R')
library(sf)
library(sp)
library(leaflet)
```

```{r split_data}

schools_ec <- schools_ec %>%
  mutate(
    super_region = case_when(
      region == 'Banskobystrický' | region == 'Žilinský' ~ 'Central',
      region == 'Košický' | region == 'Prešovský' ~ 'Eastern',
      TRUE ~ 'Western'
      ),
    pub_pri = case_when(
      school_board %in% c("Krajský úrad, Okresný úrad",
                          "Obec",
                          "Samosprávny kraj") ~ 'Public',
      school_board %in% c("Súkromník",
                          "Cirkev, cirkevné spoloèenstvo",
                          "Obèianske združenia") ~ 'Private',
      TRUE ~ 'Misc'
    )
    )

hs <- schools_ec %>%
    filter(type == 'Stredná odborná škola' | type == 'Gymnázium')

pr <- schools_ec %>%
  filter(type == 'Základná škola')
```

```{r summaries}

regional_pr <- pr %>%
  group_by(region, county) %>%
  summarise(
    overall = mean(overall_rating, na.rm = T),
    testovanie9 = mean(testovanie9, na.rm = T),
    t9_sj = mean(t9_sj, na.rm = T),
    t9_m = mean(t9_m, na.rm = T),
    t9_mj = mean(t9_mj, na.rm = T),
    t9_s_ja_sl = mean(t9_s_ja_sl, na.rm = T),
    pop = mean(pop_total),
    dens = mean(pop_density),
    income = mean(avg_wage),
    unempl = mean(unemployment_rate)
  )

regional_hs <- hs %>%
  group_by(region, county) %>%
  summarise(
    overall = mean(overall_rating, na.rm = T),
    maturity = mean(maturity, na.rm = T),
    mat_sj = mean(mat_sj, na.rm = T),
    mat_m = mean(mat_m, na.rm = T),
    mat_mj = mean(mat_mj, na.rm = T),
    mat_s_ja_sl = mean(mat_s_ja_sl, na.rm = T),
    mat_ajb1 = mean(mat_ajb1, na.rm = T),
    mat_ajb2 = mean(mat_ajb2, na.rm = T),
    mat_ajc1 = mean(mat_ajc1, na.rm = T),
    pop = mean(pop_total),
    dens = mean(pop_density),
    income = mean(avg_wage),
    unempl = mean(unemployment_rate),
  )

```


```{r graphs}

schools_ec %>%
  filter(type == 'Stredná odborná škola' | type == 'Gymnázium') %>%
  drop_na(mat_sj) %>%
  #arrange(desc(mat_sj)) %>% view()
  #filter(is.na(mat_)) %>% view()
  ggplot(aes(x = mat_sj, fill = type)) +
  geom_histogram(bins = 20)

schools_ec %>%
  filter(type == 'Základná škola') %>%
  drop_na(t9_m, t9_sj) %>%
  #arrange(desc(mat_sj)) %>% view()
  #filter(is.na(mat_)) %>% view()
  ggplot(aes(x = t9_sj, fill = super_region)) +
  geom_histogram(bins = 30)

schools_ec %>%
  filter(type == 'Základná škola') %>%
  drop_na(t9_m, t9_sj) %>%
  ggplot(aes(x = t9_sj, y = t9_m, color = super_region)) +
  geom_point()

schools_ec %>%
  filter(type == 'Základná škola') %>%
  drop_na(t9_m, t9_mj) %>%
  ggplot(aes(x = t9_mj, y = t9_m, color = super_region)) +
  geom_point()

schools_ec %>%
  filter(type == 'Základná škola') %>%
  drop_na(poc_ucitelov, t9_sj) %>%
  ggplot(aes(x = poc_ucitelov, y = t9_sj)) +
  geom_point() +
  geom_smooth(method = 'lm')

regional_summary <- schools_ec %>%
  filter(type == 'Základná škola') %>%
  group_by(county) %>%
  summarise(wage = mean(avg_wage),
            overall = mean(overall_rating, na.rm = T))

regional_summary %>%
  ggplot(aes(x = wage, y = overall)) +
  geom_point() +
  geom_smooth(method = 'lm')


```

```{r maps}
mapping_data <- function(data_by_county) {
  st_read('raw_data/shapes/SVK_adm2.shp') %>%
  mutate(NAME_2 = case_when(
    NAME_2 == 'Bytca' ~ 'Bytča',
    NAME_2 == 'Cadca' ~ 'Čadca',
    NAME_2 == 'Turcianske Teplice' ~ 'Turčianske Teplice',
    NAME_2 == 'Lucenec' ~ 'Lučenec',
    NAME_2 == 'Šala' ~ 'Šaľa',
    NAME_2 == 'Topolcany' ~ 'Topoľčany',
    NAME_2 == 'Levoca' ~ 'Levoča',
    NAME_2 == 'Stará Lubovna' ~ 'Stará Ľubovňa',
    NAME_2 == 'Trencín' ~ 'Trenčín',
    NAME_2 == 'Pieštany' ~ 'Piešťany',
    NAME_2 == 'Velký Krtíš' ~ 'Veľký Krtíš',
    NAME_2 == 'Rožnava' ~ 'Rožňava',
    NAME_2 == 'Vranov nad Toplou' ~ 'Vranov nad Topľou',
    NAME_2 == 'Košice-okolie' ~ 'Košice - okolie',
    TRUE ~ NAME_2
  )) %>%
  mutate(NAME_2 = as_factor(NAME_2),
         county = NAME_2) %>%
  full_join(data_by_county, by = 'county')
}

geo_pr <- mapping_data(regional_pr)
geo_hs <- mapping_data(regional_hs)
  
pal_pr_overall <- colorNumeric(
  palette = "plasma",
  domain = geo_pr$overall,
  reverse = TRUE)

leaflet(geo_pr) %>%
  addTiles() %>%
  addPolygons(
    stroke = F,
    fillOpacity = .9,
    smoothFactor = 0.2,
    fillColor = ~ pal_pr_overall(overall),
    label = ~paste(
      county, ': ', round(overall, 2), sep = ''
      )
  ) %>%
  addLegend(
    position = 'bottomright',
    pal = pal_pr_overall,
    values = ~overall,
    title = 'Average Rating of Primary Schools',
  )

pal_pr_income <- colorNumeric(
  palette = "Blues",
  domain = geo_pr$income,
  reverse = FALSE)

leaflet(geo_pr) %>%
  addTiles() %>%
  addPolygons(
    stroke = F,
    fillOpacity = .9,
    smoothFactor = 0.2,
    fillColor = ~ pal_pr_income(income),
    label = ~paste(
      county, ': ', round(income, 2), '€', sep = ''
      )
  ) %>%
  addLegend(
    position = 'bottomright',
    pal = pal_pr_income,
    values = ~income,
    title = 'Average Monthly Salary',
    labFormat = labelFormat(prefix = '€')
  )

pal_hs_mat <- colorNumeric(
  palette = "plasma",
  domain = geo_hs$mat_m
)

leaflet(geo_hs) %>%
  addTiles() %>%
  addPolygons(
    stroke = F,
    fillOpacity = 0.9,
    smoothFactor = 0.3,
    fillColor = ~pal_hs_mat(mat_m)
  )

```







